// src/lib/data.ts
// Single source of truth for all DSA content

export const TOPIC_META: Record<string, {
  name: string; icon: string; sub: string; order: number;
  resources: { title: string; url: string; type: "article" | "video" | "book" }[];
  concepts: string[];
  timelineWeeks: [number, number];
}> = {
  arrays: {
    name: "Arrays & Strings", icon: "▦", order: 1,
    sub: "Foundation of DSA — master in-place ops, prefix sums, and string manipulation.",
    timelineWeeks: [1, 2],
    concepts: [
      "Array traversal and indexing (O(1) access)",
      "In-place modification — two pointer swap pattern",
      "Prefix sum array — range query in O(1)",
      "Sliding window — fixed and variable size",
      "Kadane's algorithm — maximum subarray",
      "Matrix operations — rotate, spiral, zeroes",
      "String hashing — anagram and palindrome checks",
    ],
    resources: [
      { title: "Arrays 101 — LeetCode Explore", url: "https://leetcode.com/explore/learn/card/fun-with-arrays/", type: "article" },
      { title: "Prefix Sum Explained — NeetCode", url: "https://www.youtube.com/watch?v=7pJo_rM0z_s", type: "video" },
      { title: "Sliding Window Pattern — NeetCode", url: "https://www.youtube.com/watch?v=jM2dhDPCMXo", type: "video" },
      { title: "Array Patterns — cp-algorithms.com", url: "https://cp-algorithms.com/sequences/subsequences.html", type: "article" },
      { title: "Striver Arrays Series", url: "https://takeuforward.org/data-structure/arrays/", type: "video" },
    ],
  },
  hashing: {
    name: "Hashing", icon: "#", order: 2,
    sub: "HashMap and HashSet — turn O(n²) brute force into O(n) with smart lookups.",
    timelineWeeks: [2, 3],
    concepts: [
      "Hash function and collision handling",
      "HashMap — frequency count, grouping, lookup",
      "HashSet — duplicate detection, union/intersection",
      "Two-sum pattern — complement lookup",
      "Anagram grouping — sorted key / char-freq key",
      "Sliding window + HashMap — at-most K distinct",
      "LRU Cache — HashMap + Doubly Linked List",
    ],
    resources: [
      { title: "Hash Table — LeetCode Explore Card", url: "https://leetcode.com/explore/learn/card/hash-table/", type: "article" },
      { title: "HashMap Patterns — NeetCode", url: "https://www.youtube.com/watch?v=KLlXCFG5TnA", type: "video" },
      { title: "Hashing in Competitive Programming", url: "https://cp-algorithms.com/string/string-hashing.html", type: "article" },
      { title: "Striver Hashing Series", url: "https://takeuforward.org/hashing/hashing-maps-time-complexity-discussion/", type: "article" },
    ],
  },
  twopointers: {
    name: "Two Pointers", icon: "↔", order: 3,
    sub: "Left-right or slow-fast pointers — eliminate nested loops, reduce to O(n).",
    timelineWeeks: [3, 3],
    concepts: [
      "Opposite direction pointers — sorted array problems",
      "Same direction pointers — remove/filter in-place",
      "Dutch National Flag — 3-way partition",
      "3Sum and 4Sum — fix one, two-pointer the rest",
      "Palindrome check — left-right convergence",
      "Trapping Rain Water — max from both sides",
    ],
    resources: [
      { title: "Two Pointers — LeetCode Explore", url: "https://leetcode.com/explore/learn/card/array-and-string/205/array-two-pointer-technique/", type: "article" },
      { title: "Two Pointer Technique — NeetCode", url: "https://www.youtube.com/watch?v=jzZsG8n2R9A", type: "video" },
      { title: "Two Pointer Problems List", url: "https://leetcode.com/tag/two-pointers/", type: "article" },
    ],
  },
  sliding: {
    name: "Sliding Window", icon: "⊡", order: 4,
    sub: "Maintain a window with a constraint — key for substring/subarray problems.",
    timelineWeeks: [3, 4],
    concepts: [
      "Fixed-size window — max/min in window",
      "Variable-size window — expand right, shrink left",
      "Window + HashMap — character frequency",
      "At most K distinct characters pattern",
      "Minimum window containing target",
      "Monotonic deque — sliding window maximum",
    ],
    resources: [
      { title: "Sliding Window Pattern Guide", url: "https://leetcode.com/discuss/general-discussion/657507/sliding-window-for-beginners", type: "article" },
      { title: "Sliding Window — NeetCode Playlist", url: "https://www.youtube.com/watch?v=jM2dhDPCMXo", type: "video" },
      { title: "Variable Sliding Window — Striver", url: "https://takeuforward.org/data-structure/sliding-window-maximum/", type: "article" },
    ],
  },
  stack: {
    name: "Stack & Queue", icon: "⊟", order: 5,
    sub: "LIFO/FIFO and monotonic stack — solve span, histogram, and bracket problems.",
    timelineWeeks: [4, 5],
    concepts: [
      "Stack LIFO — push, pop, peek in O(1)",
      "Balanced parentheses — push open, match close",
      "Monotonic increasing/decreasing stack",
      "Next Greater Element — NGE pattern",
      "Largest Rectangle in Histogram — mono stack",
      "Queue using two stacks",
      "Deque — sliding window max/min",
    ],
    resources: [
      { title: "Stack — LeetCode Explore Card", url: "https://leetcode.com/explore/learn/card/queue-stack/", type: "article" },
      { title: "Monotonic Stack Explained", url: "https://www.youtube.com/watch?v=Dq_ObZwTY_Q", type: "video" },
      { title: "Stack Problems — Striver", url: "https://takeuforward.org/data-structure/stack-and-queue/", type: "article" },
    ],
  },
  linkedlist: {
    name: "Linked List", icon: "⊸", order: 6,
    sub: "Pointer manipulation — Floyd's cycle, slow-fast, and dummy node patterns.",
    timelineWeeks: [5, 6],
    concepts: [
      "Singly linked list — insertion, deletion, traversal",
      "Reverse a linked list — iterative and recursive",
      "Slow-fast pointers — middle, cycle detection",
      "Floyd's cycle detection algorithm",
      "Merge two sorted lists",
      "Dummy head node pattern",
      "Doubly linked list for LRU Cache",
    ],
    resources: [
      { title: "Linked List — LeetCode Explore Card", url: "https://leetcode.com/explore/learn/card/linked-list/", type: "article" },
      { title: "Linked List Playlist — NeetCode", url: "https://www.youtube.com/watch?v=G0_I-ZF0S38", type: "video" },
      { title: "Striver Linked List Series", url: "https://takeuforward.org/linked-list/", type: "article" },
    ],
  },
  trees: {
    name: "Trees", icon: "🌲", order: 7,
    sub: "BFS/DFS, BST, LCA, path sum — the most frequent topic in FAANG interviews.",
    timelineWeeks: [7, 9],
    concepts: [
      "Tree traversal — Inorder, Preorder, Postorder",
      "Level order traversal — BFS with queue",
      "Height/depth — recursive DFS",
      "Binary Search Tree — insert, delete, search",
      "BST validation — min/max range propagation",
      "Lowest Common Ancestor (LCA)",
      "Diameter and path sum — return value trick",
      "Serialize/Deserialize binary tree",
    ],
    resources: [
      { title: "Binary Tree — LeetCode Explore Card", url: "https://leetcode.com/explore/learn/card/data-structure-tree/", type: "article" },
      { title: "Trees Playlist — NeetCode", url: "https://www.youtube.com/watch?v=OnSn2XEQ4MY", type: "video" },
      { title: "Striver Tree Series (Full)", url: "https://takeuforward.org/binary-tree/", type: "article" },
      { title: "BST Algorithms — cp-algorithms", url: "https://cp-algorithms.com/data_structures/treap.html", type: "article" },
    ],
  },
  graphs: {
    name: "Graphs", icon: "⬡", order: 8,
    sub: "BFS/DFS on grids, Union-Find, Dijkstra, Topo Sort — common in senior roles.",
    timelineWeeks: [10, 12],
    concepts: [
      "Graph representation — adjacency list vs matrix",
      "BFS — shortest path in unweighted graph",
      "DFS — connected components, cycle detection",
      "Grid as graph — 4-directional BFS/DFS",
      "Union-Find (DSU) — path compression + rank",
      "Topological Sort — Kahn's BFS algorithm",
      "Dijkstra's algorithm — min-heap based",
      "Bellman-Ford — negative weights",
      "Cycle detection — directed vs undirected",
    ],
    resources: [
      { title: "Graph Theory — William Fiset", url: "https://www.youtube.com/playlist?list=PLDV1Zeh2NRsDGO4--qE8yH72HFL1Km93P", type: "video" },
      { title: "Graph Algorithms — NeetCode", url: "https://www.youtube.com/watch?v=tWVWeAqZ0WU", type: "video" },
      { title: "Striver Graph Series", url: "https://takeuforward.org/graph/", type: "article" },
      { title: "Graph Algorithms — cp-algorithms", url: "https://cp-algorithms.com/graph/", type: "article" },
    ],
  },
  dp: {
    name: "Dynamic Programming", icon: "◈", order: 9,
    sub: "8 core DP patterns — master memoization first, then tabulation, then space opt.",
    timelineWeeks: [13, 16],
    concepts: [
      "Memoization — top-down with cache",
      "Tabulation — bottom-up DP table",
      "1D DP — Fibonacci, House Robber, Climbing Stairs",
      "2D DP — Unique Paths, Edit Distance, LCS",
      "0/1 Knapsack — include or exclude item",
      "Unbounded Knapsack — Coin Change",
      "Longest Increasing Subsequence (LIS) — O(n log n)",
      "Interval DP — Burst Balloons, Matrix Chain",
      "DP on strings — LCS, Edit Distance, Regex",
    ],
    resources: [
      { title: "DP Patterns — Aladdin Persson", url: "https://leetcode.com/discuss/general-discussion/458695/dynamic-programming-patterns", type: "article" },
      { title: "DP Playlist — NeetCode (Full)", url: "https://www.youtube.com/watch?v=mBNrRy2_hVs", type: "video" },
      { title: "Striver DP Series (Must Watch)", url: "https://takeuforward.org/dynamic-programming/", type: "video" },
      { title: "DP — MIT OpenCourseWare", url: "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/", type: "article" },
    ],
  },
  bsearch: {
    name: "Binary Search", icon: "⊘", order: 10,
    sub: "Not just sorted arrays — apply on the answer space for min/max problems.",
    timelineWeeks: [6, 7],
    concepts: [
      "Classic binary search — lo, hi, mid pattern",
      "Left/right boundary search",
      "Rotated sorted array — modified binary search",
      "Binary search on answer space — monotonic check",
      "Minimize maximum / maximize minimum problems",
      "Binary search on 2D matrix",
      "Upper/lower bound implementations",
    ],
    resources: [
      { title: "Binary Search — LeetCode Explore Card", url: "https://leetcode.com/explore/learn/card/binary-search/", type: "article" },
      { title: "Binary Search Patterns — NeetCode", url: "https://www.youtube.com/watch?v=s4DPM8ct1pI", type: "video" },
      { title: "Binary Search on Answer — Striver", url: "https://takeuforward.org/binary-search/", type: "article" },
    ],
  },
  heap: {
    name: "Heap / Priority Queue", icon: "△", order: 11,
    sub: "Top-K problems, merge K sorted, median from stream — min/max heap patterns.",
    timelineWeeks: [7, 8],
    concepts: [
      "Min-heap and Max-heap — insert/extract O(log n)",
      "Heapify — build heap in O(n)",
      "Top-K elements — min-heap of size K",
      "Merge K sorted arrays — heap with (val, row, col)",
      "Two heaps — median from data stream",
      "K-way merge pattern",
      "Task scheduling with frequency heap",
    ],
    resources: [
      { title: "Heap — LeetCode Explore Card", url: "https://leetcode.com/explore/learn/card/heap/", type: "article" },
      { title: "Heap Playlist — NeetCode", url: "https://www.youtube.com/watch?v=t0Cq6tVNRBA", type: "video" },
      { title: "Priority Queue — Striver", url: "https://takeuforward.org/heap/", type: "article" },
    ],
  },
  backtrack: {
    name: "Backtracking", icon: "↩", order: 12,
    sub: "DFS with undo — generate subsets, permutations, combinations. Draw the tree.",
    timelineWeeks: [9, 10],
    concepts: [
      "Decision tree mental model",
      "Subsets — include or skip each element",
      "Permutations — swap-based generation",
      "Combinations with constraints",
      "Pruning — skip invalid branches early",
      "Deduplication — sort + skip duplicates",
      "N-Queens — row-by-row with column/diagonal sets",
    ],
    resources: [
      { title: "Backtracking — NeetCode Playlist", url: "https://www.youtube.com/watch?v=pfiQ_PS1g8E", type: "video" },
      { title: "Backtracking Template — LeetCode", url: "https://leetcode.com/discuss/general-discussion/136503/what-is-backtracking", type: "article" },
      { title: "Striver Backtracking", url: "https://takeuforward.org/recursion/", type: "article" },
    ],
  },
  greedy: {
    name: "Greedy", icon: "⚡", order: 13,
    sub: "Locally optimal choices — sort + scan patterns for interval and scheduling problems.",
    timelineWeeks: [11, 12],
    concepts: [
      "Greedy vs DP — when greedy is sufficient",
      "Activity selection — sort by end time",
      "Interval merge — sort by start, extend end",
      "Jump game — track farthest reachable",
      "Gas station — circular prefix sum argument",
      "Fractional knapsack — sort by value/weight",
    ],
    resources: [
      { title: "Greedy Algorithms — NeetCode", url: "https://www.youtube.com/watch?v=7WbRB7dSyvc", type: "video" },
      { title: "Greedy — cp-algorithms", url: "https://cp-algorithms.com/greedy/", type: "article" },
      { title: "Striver Greedy", url: "https://takeuforward.org/greedy-algorithm/", type: "article" },
    ],
  },
  trie: {
    name: "Trie", icon: "⊕", order: 14,
    sub: "Prefix tree for word/autocomplete problems — O(L) insert and search.",
    timelineWeeks: [13, 13],
    concepts: [
      "Trie node structure — children array / hashmap",
      "Insert and search — O(L) time",
      "Prefix search — autocomplete pattern",
      "Word dictionary with wildcards (DFS)",
      "Word Search II — Trie + Backtracking",
      "Maximum XOR — binary trie",
    ],
    resources: [
      { title: "Implement Trie — NeetCode", url: "https://www.youtube.com/watch?v=oobqoCJlHA0", type: "video" },
      { title: "Trie Data Structure — Striver", url: "https://takeuforward.org/trie/", type: "article" },
      { title: "Trie — LeetCode Explore Card", url: "https://leetcode.com/explore/learn/card/trie/", type: "article" },
    ],
  },
  bitwise: {
    name: "Bit Manipulation", icon: "&", order: 15,
    sub: "XOR tricks, bit counting, bitmask DP — fast O(1) solutions to hard problems.",
    timelineWeeks: [14, 14],
    concepts: [
      "Bitwise AND, OR, XOR, NOT, shifts",
      "XOR trick — a^a=0, a^0=a, find single number",
      "Brian Kernighan — count set bits in O(popcount)",
      "Power of 2 — n & (n-1) == 0",
      "Subset generation via bitmask",
      "XOR to find missing number",
      "Bitmask DP — TSP, minimum XOR subset",
    ],
    resources: [
      { title: "Bit Manipulation — NeetCode", url: "https://www.youtube.com/watch?v=NLKQEOgBAnw", type: "video" },
      { title: "Bit Tricks — cp-algorithms", url: "https://cp-algorithms.com/algebra/bit-manipulation.html", type: "article" },
      { title: "Bitwise Guide — Striver", url: "https://takeuforward.org/bit-manipulation/", type: "article" },
    ],
  },
  strings: {
    name: "Strings", icon: "Aa", order: 16,
    sub: "String problems are array problems in disguise. Master sliding window, two pointers, and hashing on characters.",
    timelineWeeks: [2, 3],
    concepts: [
      "String as char array — iterate with index or for..of",
      "Two pointers for palindrome — converge from both ends",
      "Expand around center — odd and even length palindromes",
      "Anagram detection — sorted key or frequency array[26]",
      "Sliding window + HashMap — longest without repeating, min window",
      "KMP algorithm — pattern matching in O(n+m)",
      "Stack for expression parsing — decode string, calculator",
      "String building — use array + join, never += in a loop",
    ],
    resources: [
      { title: "String — LeetCode Explore Card", url: "https://leetcode.com/explore/learn/card/array-and-string/", type: "article" },
      { title: "String Problems Playlist — NeetCode", url: "https://www.youtube.com/watch?v=xyGGFX25xFQ", type: "video" },
      { title: "KMP Algorithm Explained — Abdul Bari", url: "https://www.youtube.com/watch?v=V5-7GzOfADQ", type: "video" },
      { title: "String Hashing — cp-algorithms", url: "https://cp-algorithms.com/string/string-hashing.html", type: "article" },
      { title: "Striver String Series", url: "https://takeuforward.org/string/", type: "article" },
    ],
  },
  math: {
    name: "Math & Number Theory", icon: "∑", order: 17,
    sub: "Sieve, GCD, fast exponentiation — math problems reward knowing the right formula over brute force.",
    timelineWeeks: [15, 15],
    concepts: [
      "Sieve of Eratosthenes — all primes up to n in O(n log log n)",
      "Euclidean GCD — gcd(a,b) = gcd(b, a%b), iterative is O(log min(a,b))",
      "LCM — lcm(a,b) = a / gcd(a,b) * b (divide first to avoid overflow)",
      "Fast exponentiation — repeated squaring, O(log n)",
      "Modular arithmetic — (a*b)%m = ((a%m)*(b%m))%m",
      "Prime factorization — trial division up to sqrt(n)",
      "Digit manipulation — last digit: n%10, remove last: Math.floor(n/10)",
      "Factorial trailing zeros — count factors of 5: n/5 + n/25 + ...",
    ],
    resources: [
      { title: "Math — cp-algorithms algebra", url: "https://cp-algorithms.com/algebra/", type: "article" },
      { title: "Number Theory Problems — LeetCode", url: "https://leetcode.com/tag/math/", type: "article" },
      { title: "Sieve of Eratosthenes — Khan Academy", url: "https://www.khanacademy.org/computing/computer-science/cryptography/comp-number-theory/a/sieve-of-eratosthenes", type: "article" },
      { title: "Fast Exponentiation — cp-algorithms", url: "https://cp-algorithms.com/algebra/binary-exp.html", type: "article" },
      { title: "Math Problems — Striver", url: "https://takeuforward.org/maths/", type: "video" },
    ],
  },
  intervals: {
    name: "Intervals", icon: "▬", order: 18,
    sub: "Sort then sweep — merging, inserting, and scheduling intervals are all one pattern away.",
    timelineWeeks: [4, 5],
    concepts: [
      "Sort by start time — converts 2D interval problem to 1D scan",
      "Merge overlapping — if curr.start <= prev.end, extend prev.end = max",
      "Insert interval — three phases: before, overlap, after",
      "Non-overlapping max — sort by END time, greedily pick earliest-ending",
      "Minimum meeting rooms — min-heap of end times, heap size = rooms in use",
      "Two pointers on sorted interval arrays — intersection of two lists",
      "Sweep line — sort all start/end events, count active intervals",
    ],
    resources: [
      { title: "Interval Problems — LeetCode Tag", url: "https://leetcode.com/tag/intervals/", type: "article" },
      { title: "Merge Intervals — NeetCode", url: "https://www.youtube.com/watch?v=44H3cEC2fFM", type: "video" },
      { title: "Meeting Rooms II — NeetCode", url: "https://www.youtube.com/watch?v=FdzJmTx9TWE", type: "video" },
      { title: "Interval Scheduling — cp-algorithms", url: "https://cp-algorithms.com/schedules/schedule_two_machines.html", type: "article" },
      { title: "Greedy Interval Problems — Striver", url: "https://takeuforward.org/greedy-algorithm/", type: "article" },
    ],
  },
};

export const PROBLEMS: Record<string, {
  number: number; title: string; difficulty: "easy" | "medium" | "hard";
  pattern: string; lcUrl: string;
}[]> = {
  arrays: [
    { number:1, title:"Two Sum", difficulty:"easy", pattern:"Hashing", lcUrl:"https://leetcode.com/problems/two-sum/" },
    { number:2, title:"Best Time to Buy and Sell Stock", difficulty:"easy", pattern:"Sliding Window", lcUrl:"https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
    { number:3, title:"Contains Duplicate", difficulty:"easy", pattern:"Hashing", lcUrl:"https://leetcode.com/problems/contains-duplicate/" },
    { number:4, title:"Maximum Subarray", difficulty:"medium", pattern:"Kadane's", lcUrl:"https://leetcode.com/problems/maximum-subarray/" },
    { number:5, title:"Product of Array Except Self", difficulty:"medium", pattern:"Prefix Sum", lcUrl:"https://leetcode.com/problems/product-of-array-except-self/" },
    { number:6, title:"Maximum Product Subarray", difficulty:"medium", pattern:"DP", lcUrl:"https://leetcode.com/problems/maximum-product-subarray/" },
    { number:7, title:"Find Minimum in Rotated Sorted Array", difficulty:"medium", pattern:"Binary Search", lcUrl:"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
    { number:8, title:"Search in Rotated Sorted Array", difficulty:"medium", pattern:"Binary Search", lcUrl:"https://leetcode.com/problems/search-in-rotated-sorted-array/" },
    { number:9, title:"3Sum", difficulty:"medium", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/3sum/" },
    { number:10, title:"Container With Most Water", difficulty:"medium", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/container-with-most-water/" },
    { number:11, title:"Trapping Rain Water", difficulty:"hard", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/trapping-rain-water/" },
    { number:12, title:"Minimum Window Substring", difficulty:"hard", pattern:"Sliding Window", lcUrl:"https://leetcode.com/problems/minimum-window-substring/" },
    { number:13, title:"Longest Consecutive Sequence", difficulty:"medium", pattern:"Hashing", lcUrl:"https://leetcode.com/problems/longest-consecutive-sequence/" },
    { number:14, title:"Subarray Sum Equals K", difficulty:"medium", pattern:"Prefix Sum", lcUrl:"https://leetcode.com/problems/subarray-sum-equals-k/" },
    { number:15, title:"Spiral Matrix", difficulty:"medium", pattern:"Matrix", lcUrl:"https://leetcode.com/problems/spiral-matrix/" },
    { number:16, title:"Set Matrix Zeroes", difficulty:"medium", pattern:"Matrix", lcUrl:"https://leetcode.com/problems/set-matrix-zeroes/" },
    { number:17, title:"Rotate Image", difficulty:"medium", pattern:"Matrix", lcUrl:"https://leetcode.com/problems/rotate-image/" },
    { number:18, title:"Jump Game", difficulty:"medium", pattern:"Greedy", lcUrl:"https://leetcode.com/problems/jump-game/" },
    { number:19, title:"Merge Intervals", difficulty:"medium", pattern:"Intervals", lcUrl:"https://leetcode.com/problems/merge-intervals/" },
    { number:20, title:"Non-overlapping Intervals", difficulty:"medium", pattern:"Intervals", lcUrl:"https://leetcode.com/problems/non-overlapping-intervals/" },
  ],
  hashing: [
    { number:1, title:"Two Sum", difficulty:"easy", pattern:"HashMap", lcUrl:"https://leetcode.com/problems/two-sum/" },
    { number:2, title:"Valid Anagram", difficulty:"easy", pattern:"HashMap", lcUrl:"https://leetcode.com/problems/valid-anagram/" },
    { number:3, title:"Ransom Note", difficulty:"easy", pattern:"HashMap", lcUrl:"https://leetcode.com/problems/ransom-note/" },
    { number:4, title:"Isomorphic Strings", difficulty:"easy", pattern:"HashMap", lcUrl:"https://leetcode.com/problems/isomorphic-strings/" },
    { number:5, title:"Word Pattern", difficulty:"easy", pattern:"HashMap", lcUrl:"https://leetcode.com/problems/word-pattern/" },
    { number:6, title:"Group Anagrams", difficulty:"medium", pattern:"HashMap", lcUrl:"https://leetcode.com/problems/group-anagrams/" },
    { number:7, title:"Top K Frequent Elements", difficulty:"medium", pattern:"Bucket Sort", lcUrl:"https://leetcode.com/problems/top-k-frequent-elements/" },
    { number:8, title:"Longest Consecutive Sequence", difficulty:"medium", pattern:"HashSet", lcUrl:"https://leetcode.com/problems/longest-consecutive-sequence/" },
    { number:9, title:"Encode and Decode Strings", difficulty:"medium", pattern:"Design", lcUrl:"https://leetcode.com/problems/encode-and-decode-strings/" },
    { number:10, title:"LRU Cache", difficulty:"medium", pattern:"HashMap+DLL", lcUrl:"https://leetcode.com/problems/lru-cache/" },
  ],
  twopointers: [
    { number:1, title:"Valid Palindrome", difficulty:"easy", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/valid-palindrome/" },
    { number:2, title:"Remove Duplicates from Sorted Array", difficulty:"easy", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/remove-duplicates-from-sorted-array/" },
    { number:3, title:"Move Zeroes", difficulty:"easy", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/move-zeroes/" },
    { number:4, title:"Two Sum II", difficulty:"medium", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/" },
    { number:5, title:"3Sum", difficulty:"medium", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/3sum/" },
    { number:6, title:"Container With Most Water", difficulty:"medium", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/container-with-most-water/" },
    { number:7, title:"4Sum", difficulty:"medium", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/4sum/" },
    { number:8, title:"Sort Colors", difficulty:"medium", pattern:"Dutch Flag", lcUrl:"https://leetcode.com/problems/sort-colors/" },
    { number:9, title:"Boats to Save People", difficulty:"medium", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/boats-to-save-people/" },
    { number:10, title:"Trapping Rain Water", difficulty:"hard", pattern:"Two Pointers", lcUrl:"https://leetcode.com/problems/trapping-rain-water/" },
  ],
  sliding: [
    { number:1, title:"Best Time to Buy and Sell Stock", difficulty:"easy", pattern:"Sliding Window", lcUrl:"https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
    { number:2, title:"Maximum Average Subarray I", difficulty:"easy", pattern:"Fixed Window", lcUrl:"https://leetcode.com/problems/maximum-average-subarray-i/" },
    { number:3, title:"Longest Substring Without Repeating Characters", difficulty:"medium", pattern:"Variable Window", lcUrl:"https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
    { number:4, title:"Longest Repeating Character Replacement", difficulty:"medium", pattern:"Variable Window", lcUrl:"https://leetcode.com/problems/longest-repeating-character-replacement/" },
    { number:5, title:"Permutation in String", difficulty:"medium", pattern:"Fixed Window", lcUrl:"https://leetcode.com/problems/permutation-in-string/" },
    { number:6, title:"Find All Anagrams in a String", difficulty:"medium", pattern:"Fixed Window", lcUrl:"https://leetcode.com/problems/find-all-anagrams-in-a-string/" },
    { number:7, title:"Max Consecutive Ones III", difficulty:"medium", pattern:"Variable Window", lcUrl:"https://leetcode.com/problems/max-consecutive-ones-iii/" },
    { number:8, title:"Minimum Size Subarray Sum", difficulty:"medium", pattern:"Variable Window", lcUrl:"https://leetcode.com/problems/minimum-size-subarray-sum/" },
    { number:9, title:"Subarray Product Less Than K", difficulty:"medium", pattern:"Variable Window", lcUrl:"https://leetcode.com/problems/subarray-product-less-than-k/" },
    { number:10, title:"Minimum Window Substring", difficulty:"hard", pattern:"Variable Window", lcUrl:"https://leetcode.com/problems/minimum-window-substring/" },
    { number:11, title:"Sliding Window Maximum", difficulty:"hard", pattern:"Monotonic Deque", lcUrl:"https://leetcode.com/problems/sliding-window-maximum/" },
  ],
  stack: [
    { number:1, title:"Valid Parentheses", difficulty:"easy", pattern:"Stack", lcUrl:"https://leetcode.com/problems/valid-parentheses/" },
    { number:2, title:"Next Greater Element I", difficulty:"easy", pattern:"Monotonic Stack", lcUrl:"https://leetcode.com/problems/next-greater-element-i/" },
    { number:3, title:"Min Stack", difficulty:"medium", pattern:"Stack", lcUrl:"https://leetcode.com/problems/min-stack/" },
    { number:4, title:"Evaluate Reverse Polish Notation", difficulty:"medium", pattern:"Stack", lcUrl:"https://leetcode.com/problems/evaluate-reverse-polish-notation/" },
    { number:5, title:"Generate Parentheses", difficulty:"medium", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/generate-parentheses/" },
    { number:6, title:"Daily Temperatures", difficulty:"medium", pattern:"Monotonic Stack", lcUrl:"https://leetcode.com/problems/daily-temperatures/" },
    { number:7, title:"Car Fleet", difficulty:"medium", pattern:"Stack", lcUrl:"https://leetcode.com/problems/car-fleet/" },
    { number:8, title:"Decode String", difficulty:"medium", pattern:"Stack", lcUrl:"https://leetcode.com/problems/decode-string/" },
    { number:9, title:"Asteroid Collision", difficulty:"medium", pattern:"Stack", lcUrl:"https://leetcode.com/problems/asteroid-collision/" },
    { number:10, title:"Remove K Digits", difficulty:"medium", pattern:"Monotonic Stack", lcUrl:"https://leetcode.com/problems/remove-k-digits/" },
    { number:11, title:"Largest Rectangle in Histogram", difficulty:"hard", pattern:"Monotonic Stack", lcUrl:"https://leetcode.com/problems/largest-rectangle-in-histogram/" },
    { number:12, title:"Maximum Frequency Stack", difficulty:"hard", pattern:"Stack Design", lcUrl:"https://leetcode.com/problems/maximum-frequency-stack/" },
  ],
  linkedlist: [
    { number:1, title:"Reverse Linked List", difficulty:"easy", pattern:"Pointers", lcUrl:"https://leetcode.com/problems/reverse-linked-list/" },
    { number:2, title:"Merge Two Sorted Lists", difficulty:"easy", pattern:"Merge", lcUrl:"https://leetcode.com/problems/merge-two-sorted-lists/" },
    { number:3, title:"Linked List Cycle", difficulty:"easy", pattern:"Floyd's", lcUrl:"https://leetcode.com/problems/linked-list-cycle/" },
    { number:4, title:"Palindrome Linked List", difficulty:"easy", pattern:"Slow-Fast", lcUrl:"https://leetcode.com/problems/palindrome-linked-list/" },
    { number:5, title:"Remove Duplicates from Sorted List", difficulty:"easy", pattern:"Pointers", lcUrl:"https://leetcode.com/problems/remove-duplicates-from-sorted-list/" },
    { number:6, title:"Reorder List", difficulty:"medium", pattern:"Slow-Fast", lcUrl:"https://leetcode.com/problems/reorder-list/" },
    { number:7, title:"Remove Nth Node From End", difficulty:"medium", pattern:"Slow-Fast", lcUrl:"https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
    { number:8, title:"Copy List with Random Pointer", difficulty:"medium", pattern:"HashMap", lcUrl:"https://leetcode.com/problems/copy-list-with-random-pointer/" },
    { number:9, title:"Add Two Numbers", difficulty:"medium", pattern:"Simulation", lcUrl:"https://leetcode.com/problems/add-two-numbers/" },
    { number:10, title:"Find the Duplicate Number", difficulty:"medium", pattern:"Floyd's", lcUrl:"https://leetcode.com/problems/find-the-duplicate-number/" },
    { number:11, title:"LRU Cache", difficulty:"medium", pattern:"DLL+HashMap", lcUrl:"https://leetcode.com/problems/lru-cache/" },
    { number:12, title:"Merge K Sorted Lists", difficulty:"hard", pattern:"Heap", lcUrl:"https://leetcode.com/problems/merge-k-sorted-lists/" },
    { number:13, title:"Reverse Nodes in K-Group", difficulty:"hard", pattern:"Pointers", lcUrl:"https://leetcode.com/problems/reverse-nodes-in-k-group/" },
  ],
  trees: [
    { number:1, title:"Invert Binary Tree", difficulty:"easy", pattern:"DFS", lcUrl:"https://leetcode.com/problems/invert-binary-tree/" },
    { number:2, title:"Maximum Depth of Binary Tree", difficulty:"easy", pattern:"DFS", lcUrl:"https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
    { number:3, title:"Diameter of Binary Tree", difficulty:"easy", pattern:"DFS", lcUrl:"https://leetcode.com/problems/diameter-of-binary-tree/" },
    { number:4, title:"Balanced Binary Tree", difficulty:"easy", pattern:"DFS", lcUrl:"https://leetcode.com/problems/balanced-binary-tree/" },
    { number:5, title:"Same Tree", difficulty:"easy", pattern:"DFS", lcUrl:"https://leetcode.com/problems/same-tree/" },
    { number:6, title:"Subtree of Another Tree", difficulty:"easy", pattern:"DFS", lcUrl:"https://leetcode.com/problems/subtree-of-another-tree/" },
    { number:7, title:"Binary Tree Level Order Traversal", difficulty:"medium", pattern:"BFS", lcUrl:"https://leetcode.com/problems/binary-tree-level-order-traversal/" },
    { number:8, title:"Binary Tree Right Side View", difficulty:"medium", pattern:"BFS", lcUrl:"https://leetcode.com/problems/binary-tree-right-side-view/" },
    { number:9, title:"Count Good Nodes in Binary Tree", difficulty:"medium", pattern:"DFS", lcUrl:"https://leetcode.com/problems/count-good-nodes-in-binary-tree/" },
    { number:10, title:"Validate Binary Search Tree", difficulty:"medium", pattern:"BST", lcUrl:"https://leetcode.com/problems/validate-binary-search-tree/" },
    { number:11, title:"Kth Smallest Element in BST", difficulty:"medium", pattern:"BST", lcUrl:"https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
    { number:12, title:"Lowest Common Ancestor of BST", difficulty:"medium", pattern:"BST", lcUrl:"https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
    { number:13, title:"Construct Binary Tree from Preorder and Inorder", difficulty:"medium", pattern:"Recursion", lcUrl:"https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
    { number:14, title:"Binary Tree Maximum Path Sum", difficulty:"hard", pattern:"DFS", lcUrl:"https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
    { number:15, title:"Serialize and Deserialize Binary Tree", difficulty:"hard", pattern:"BFS/DFS", lcUrl:"https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
    { number:16, title:"Word Ladder", difficulty:"hard", pattern:"BFS", lcUrl:"https://leetcode.com/problems/word-ladder/" },
  ],
  graphs: [
    { number:1, title:"Number of Islands", difficulty:"medium", pattern:"BFS/DFS", lcUrl:"https://leetcode.com/problems/number-of-islands/" },
    { number:2, title:"Max Area of Island", difficulty:"medium", pattern:"DFS", lcUrl:"https://leetcode.com/problems/max-area-of-island/" },
    { number:3, title:"Clone Graph", difficulty:"medium", pattern:"BFS/DFS", lcUrl:"https://leetcode.com/problems/clone-graph/" },
    { number:4, title:"Pacific Atlantic Water Flow", difficulty:"medium", pattern:"BFS/DFS", lcUrl:"https://leetcode.com/problems/pacific-atlantic-water-flow/" },
    { number:5, title:"Surrounded Regions", difficulty:"medium", pattern:"DFS", lcUrl:"https://leetcode.com/problems/surrounded-regions/" },
    { number:6, title:"Rotting Oranges", difficulty:"medium", pattern:"BFS", lcUrl:"https://leetcode.com/problems/rotting-oranges/" },
    { number:7, title:"Course Schedule", difficulty:"medium", pattern:"Topological Sort", lcUrl:"https://leetcode.com/problems/course-schedule/" },
    { number:8, title:"Course Schedule II", difficulty:"medium", pattern:"Topological Sort", lcUrl:"https://leetcode.com/problems/course-schedule-ii/" },
    { number:9, title:"Redundant Connection", difficulty:"medium", pattern:"Union Find", lcUrl:"https://leetcode.com/problems/redundant-connection/" },
    { number:10, title:"Number of Connected Components", difficulty:"medium", pattern:"Union Find", lcUrl:"https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/" },
    { number:11, title:"Graph Valid Tree", difficulty:"medium", pattern:"Union Find", lcUrl:"https://leetcode.com/problems/graph-valid-tree/" },
    { number:12, title:"Network Delay Time", difficulty:"medium", pattern:"Dijkstra", lcUrl:"https://leetcode.com/problems/network-delay-time/" },
    { number:13, title:"Cheapest Flights Within K Stops", difficulty:"medium", pattern:"Bellman Ford", lcUrl:"https://leetcode.com/problems/cheapest-flights-within-k-stops/" },
    { number:14, title:"Word Ladder", difficulty:"hard", pattern:"BFS", lcUrl:"https://leetcode.com/problems/word-ladder/" },
    { number:15, title:"Alien Dictionary", difficulty:"hard", pattern:"Topological Sort", lcUrl:"https://leetcode.com/problems/alien-dictionary/" },
    { number:16, title:"Swim in Rising Water", difficulty:"hard", pattern:"Dijkstra", lcUrl:"https://leetcode.com/problems/swim-in-rising-water/" },
    { number:17, title:"Find Critical and Pseudo-Critical Edges", difficulty:"hard", pattern:"MST", lcUrl:"https://leetcode.com/problems/find-critical-and-pseudo-critical-edges-in-minimum-spanning-tree/" },
  ],
  dp: [
    { number:1, title:"Climbing Stairs", difficulty:"easy", pattern:"1D DP", lcUrl:"https://leetcode.com/problems/climbing-stairs/" },
    { number:2, title:"Min Cost Climbing Stairs", difficulty:"easy", pattern:"1D DP", lcUrl:"https://leetcode.com/problems/min-cost-climbing-stairs/" },
    { number:3, title:"House Robber", difficulty:"medium", pattern:"1D DP", lcUrl:"https://leetcode.com/problems/house-robber/" },
    { number:4, title:"House Robber II", difficulty:"medium", pattern:"1D DP", lcUrl:"https://leetcode.com/problems/house-robber-ii/" },
    { number:5, title:"Longest Palindromic Substring", difficulty:"medium", pattern:"2D DP", lcUrl:"https://leetcode.com/problems/longest-palindromic-substring/" },
    { number:6, title:"Palindromic Substrings", difficulty:"medium", pattern:"2D DP", lcUrl:"https://leetcode.com/problems/palindromic-substrings/" },
    { number:7, title:"Decode Ways", difficulty:"medium", pattern:"1D DP", lcUrl:"https://leetcode.com/problems/decode-ways/" },
    { number:8, title:"Coin Change", difficulty:"medium", pattern:"Unbounded Knapsack", lcUrl:"https://leetcode.com/problems/coin-change/" },
    { number:9, title:"Maximum Product Subarray", difficulty:"medium", pattern:"1D DP", lcUrl:"https://leetcode.com/problems/maximum-product-subarray/" },
    { number:10, title:"Word Break", difficulty:"medium", pattern:"1D DP", lcUrl:"https://leetcode.com/problems/word-break/" },
    { number:11, title:"Longest Increasing Subsequence", difficulty:"medium", pattern:"LIS", lcUrl:"https://leetcode.com/problems/longest-increasing-subsequence/" },
    { number:12, title:"Partition Equal Subset Sum", difficulty:"medium", pattern:"0/1 Knapsack", lcUrl:"https://leetcode.com/problems/partition-equal-subset-sum/" },
    { number:13, title:"Unique Paths", difficulty:"medium", pattern:"2D DP", lcUrl:"https://leetcode.com/problems/unique-paths/" },
    { number:14, title:"Longest Common Subsequence", difficulty:"medium", pattern:"LCS", lcUrl:"https://leetcode.com/problems/longest-common-subsequence/" },
    { number:15, title:"Edit Distance", difficulty:"medium", pattern:"LCS", lcUrl:"https://leetcode.com/problems/edit-distance/" },
    { number:16, title:"Interleaving String", difficulty:"medium", pattern:"2D DP", lcUrl:"https://leetcode.com/problems/interleaving-string/" },
    { number:17, title:"Burst Balloons", difficulty:"hard", pattern:"Interval DP", lcUrl:"https://leetcode.com/problems/burst-balloons/" },
    { number:18, title:"Regular Expression Matching", difficulty:"hard", pattern:"2D DP", lcUrl:"https://leetcode.com/problems/regular-expression-matching/" },
    { number:19, title:"Distinct Subsequences", difficulty:"hard", pattern:"2D DP", lcUrl:"https://leetcode.com/problems/distinct-subsequences/" },
    { number:20, title:"Maximum Profit in Job Scheduling", difficulty:"hard", pattern:"DP+BinarySearch", lcUrl:"https://leetcode.com/problems/maximum-profit-in-job-scheduling/" },
  ],
  bsearch: [
    { number:1, title:"Binary Search", difficulty:"easy", pattern:"Basic", lcUrl:"https://leetcode.com/problems/binary-search/" },
    { number:2, title:"First Bad Version", difficulty:"easy", pattern:"Binary Search", lcUrl:"https://leetcode.com/problems/first-bad-version/" },
    { number:3, title:"Guess Number Higher or Lower", difficulty:"easy", pattern:"Binary Search", lcUrl:"https://leetcode.com/problems/guess-number-higher-or-lower/" },
    { number:4, title:"Search a 2D Matrix", difficulty:"medium", pattern:"Binary Search", lcUrl:"https://leetcode.com/problems/search-a-2d-matrix/" },
    { number:5, title:"Koko Eating Bananas", difficulty:"medium", pattern:"Answer Space", lcUrl:"https://leetcode.com/problems/koko-eating-bananas/" },
    { number:6, title:"Find Minimum in Rotated Sorted Array", difficulty:"medium", pattern:"Binary Search", lcUrl:"https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
    { number:7, title:"Search in Rotated Sorted Array", difficulty:"medium", pattern:"Binary Search", lcUrl:"https://leetcode.com/problems/search-in-rotated-sorted-array/" },
    { number:8, title:"Time Based Key-Value Store", difficulty:"medium", pattern:"Binary Search", lcUrl:"https://leetcode.com/problems/time-based-key-value-store/" },
    { number:9, title:"Capacity to Ship Packages", difficulty:"medium", pattern:"Answer Space", lcUrl:"https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/" },
    { number:10, title:"Find Peak Element", difficulty:"medium", pattern:"Binary Search", lcUrl:"https://leetcode.com/problems/find-peak-element/" },
    { number:11, title:"Median of Two Sorted Arrays", difficulty:"hard", pattern:"Binary Search", lcUrl:"https://leetcode.com/problems/median-of-two-sorted-arrays/" },
    { number:12, title:"Split Array Largest Sum", difficulty:"hard", pattern:"Answer Space", lcUrl:"https://leetcode.com/problems/split-array-largest-sum/" },
  ],
  heap: [
    { number:1, title:"Kth Largest Element in a Stream", difficulty:"easy", pattern:"Min Heap", lcUrl:"https://leetcode.com/problems/kth-largest-element-in-a-stream/" },
    { number:2, title:"Last Stone Weight", difficulty:"easy", pattern:"Max Heap", lcUrl:"https://leetcode.com/problems/last-stone-weight/" },
    { number:3, title:"K Closest Points to Origin", difficulty:"medium", pattern:"Min Heap", lcUrl:"https://leetcode.com/problems/k-closest-points-to-origin/" },
    { number:4, title:"Kth Largest Element in Array", difficulty:"medium", pattern:"Heap/Quickselect", lcUrl:"https://leetcode.com/problems/kth-largest-element-in-an-array/" },
    { number:5, title:"Task Scheduler", difficulty:"medium", pattern:"Max Heap", lcUrl:"https://leetcode.com/problems/task-scheduler/" },
    { number:6, title:"Design Twitter", difficulty:"medium", pattern:"Heap", lcUrl:"https://leetcode.com/problems/design-twitter/" },
    { number:7, title:"Top K Frequent Elements", difficulty:"medium", pattern:"Heap", lcUrl:"https://leetcode.com/problems/top-k-frequent-elements/" },
    { number:8, title:"Top K Frequent Words", difficulty:"medium", pattern:"Heap", lcUrl:"https://leetcode.com/problems/top-k-frequent-words/" },
    { number:9, title:"Find Median from Data Stream", difficulty:"hard", pattern:"Two Heaps", lcUrl:"https://leetcode.com/problems/find-median-from-data-stream/" },
    { number:10, title:"Merge K Sorted Lists", difficulty:"hard", pattern:"Min Heap", lcUrl:"https://leetcode.com/problems/merge-k-sorted-lists/" },
    { number:11, title:"Smallest Range Covering K Lists", difficulty:"hard", pattern:"Heap", lcUrl:"https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/" },
  ],
  backtrack: [
    { number:1, title:"Subsets", difficulty:"medium", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/subsets/" },
    { number:2, title:"Combination Sum", difficulty:"medium", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/combination-sum/" },
    { number:3, title:"Permutations", difficulty:"medium", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/permutations/" },
    { number:4, title:"Subsets II", difficulty:"medium", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/subsets-ii/" },
    { number:5, title:"Combination Sum II", difficulty:"medium", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/combination-sum-ii/" },
    { number:6, title:"Word Search", difficulty:"medium", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/word-search/" },
    { number:7, title:"Palindrome Partitioning", difficulty:"medium", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/palindrome-partitioning/" },
    { number:8, title:"Letter Combinations of Phone Number", difficulty:"medium", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
    { number:9, title:"N-Queens", difficulty:"hard", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/n-queens/" },
    { number:10, title:"Sudoku Solver", difficulty:"hard", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/sudoku-solver/" },
    { number:11, title:"N-Queens II", difficulty:"hard", pattern:"Backtracking", lcUrl:"https://leetcode.com/problems/n-queens-ii/" },
  ],
  greedy: [
    { number:1, title:"Jump Game", difficulty:"medium", pattern:"Greedy", lcUrl:"https://leetcode.com/problems/jump-game/" },
    { number:2, title:"Jump Game II", difficulty:"medium", pattern:"Greedy", lcUrl:"https://leetcode.com/problems/jump-game-ii/" },
    { number:3, title:"Gas Station", difficulty:"medium", pattern:"Greedy", lcUrl:"https://leetcode.com/problems/gas-station/" },
    { number:4, title:"Hand of Straights", difficulty:"medium", pattern:"Greedy", lcUrl:"https://leetcode.com/problems/hand-of-straights/" },
    { number:5, title:"Merge Triplets to Form Target", difficulty:"medium", pattern:"Greedy", lcUrl:"https://leetcode.com/problems/merge-triplets-to-form-a-target-triplet/" },
    { number:6, title:"Partition Labels", difficulty:"medium", pattern:"Greedy", lcUrl:"https://leetcode.com/problems/partition-labels/" },
    { number:7, title:"Valid Parenthesis String", difficulty:"medium", pattern:"Greedy", lcUrl:"https://leetcode.com/problems/valid-parenthesis-string/" },
    { number:8, title:"Non-overlapping Intervals", difficulty:"medium", pattern:"Intervals", lcUrl:"https://leetcode.com/problems/non-overlapping-intervals/" },
    { number:9, title:"Meeting Rooms II", difficulty:"medium", pattern:"Intervals+Heap", lcUrl:"https://leetcode.com/problems/meeting-rooms-ii/" },
    { number:10, title:"Candy", difficulty:"hard", pattern:"Greedy", lcUrl:"https://leetcode.com/problems/candy/" },
  ],
  trie: [
    { number:1, title:"Implement Trie (Prefix Tree)", difficulty:"medium", pattern:"Trie", lcUrl:"https://leetcode.com/problems/implement-trie-prefix-tree/" },
    { number:2, title:"Design Add and Search Words", difficulty:"medium", pattern:"Trie+DFS", lcUrl:"https://leetcode.com/problems/design-add-and-search-words-data-structure/" },
    { number:3, title:"Longest Word in Dictionary", difficulty:"medium", pattern:"Trie", lcUrl:"https://leetcode.com/problems/longest-word-in-dictionary/" },
    { number:4, title:"Replace Words", difficulty:"medium", pattern:"Trie", lcUrl:"https://leetcode.com/problems/replace-words/" },
    { number:5, title:"Map Sum Pairs", difficulty:"medium", pattern:"Trie", lcUrl:"https://leetcode.com/problems/map-sum-pairs/" },
    { number:6, title:"Maximum XOR of Two Numbers", difficulty:"medium", pattern:"Trie+Bit", lcUrl:"https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/" },
    { number:7, title:"Word Search II", difficulty:"hard", pattern:"Trie+Backtracking", lcUrl:"https://leetcode.com/problems/word-search-ii/" },
    { number:8, title:"Palindrome Pairs", difficulty:"hard", pattern:"Trie", lcUrl:"https://leetcode.com/problems/palindrome-pairs/" },
  ],
  bitwise: [
    { number:1, title:"Single Number", difficulty:"easy", pattern:"XOR", lcUrl:"https://leetcode.com/problems/single-number/" },
    { number:2, title:"Number of 1 Bits", difficulty:"easy", pattern:"Bit Count", lcUrl:"https://leetcode.com/problems/number-of-1-bits/" },
    { number:3, title:"Counting Bits", difficulty:"easy", pattern:"DP+Bit", lcUrl:"https://leetcode.com/problems/counting-bits/" },
    { number:4, title:"Reverse Bits", difficulty:"easy", pattern:"Bit Manipulation", lcUrl:"https://leetcode.com/problems/reverse-bits/" },
    { number:5, title:"Missing Number", difficulty:"easy", pattern:"XOR", lcUrl:"https://leetcode.com/problems/missing-number/" },
    { number:6, title:"Sum of Two Integers", difficulty:"medium", pattern:"Bit Manipulation", lcUrl:"https://leetcode.com/problems/sum-of-two-integers/" },
    { number:7, title:"Reverse Integer", difficulty:"medium", pattern:"Math", lcUrl:"https://leetcode.com/problems/reverse-integer/" },
    { number:8, title:"Single Number II", difficulty:"medium", pattern:"Bit Counting", lcUrl:"https://leetcode.com/problems/single-number-ii/" },
    { number:9, title:"Subsets via Bitmask", difficulty:"medium", pattern:"Bitmask", lcUrl:"https://leetcode.com/problems/subsets/" },
    { number:10, title:"Maximum XOR of Two Numbers", difficulty:"medium", pattern:"Trie+Bit", lcUrl:"https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/" },
  ],
};

// 6-month weekly plan
export const WEEKLY_PLAN: {
  week: number; title: string; topics: string[]; goals: string[];
  dailyTasks: { day: string; task: string; problems: number }[];
}[] = [
  {
    week: 1, title: "Arrays Fundamentals", topics: ["arrays"],
    goals: ["Understand time/space complexity basics", "Solve all easy array problems", "Learn prefix sum and sliding window concept"],
    dailyTasks: [
      { day: "Mon", task: "Study Arrays theory + complexity", problems: 2 },
      { day: "Tue", task: "Easy array problems (Two Sum, Contains Dup)", problems: 3 },
      { day: "Wed", task: "Prefix sum problems", problems: 2 },
      { day: "Thu", task: "Medium array problems", problems: 2 },
      { day: "Fri", task: "Matrix problems", problems: 2 },
      { day: "Sat", task: "Mixed arrays revision", problems: 3 },
      { day: "Sun", task: "Weekly test + review", problems: 0 },
    ],
  },
  {
    week: 2, title: "Hashing & Two Pointers", topics: ["hashing", "twopointers"],
    goals: ["Master HashMap/Set patterns", "Solve complement lookup problems", "Two-pointer on sorted arrays"],
    dailyTasks: [
      { day: "Mon", task: "HashMap theory + easy problems", problems: 3 },
      { day: "Tue", task: "Group Anagrams, Top K Frequent", problems: 2 },
      { day: "Wed", task: "Two Pointers concept + easy", problems: 2 },
      { day: "Thu", task: "3Sum, Container with Water", problems: 2 },
      { day: "Fri", task: "Hard hashing/pointer problems", problems: 2 },
      { day: "Sat", task: "Mixed revision + new problems", problems: 3 },
      { day: "Sun", task: "Weekly test + review", problems: 0 },
    ],
  },
  {
    week: 3, title: "Sliding Window + Binary Search", topics: ["sliding", "bsearch"],
    goals: ["Variable and fixed window mastery", "Binary search on answer space", "Solve 5+ medium problems each"],
    dailyTasks: [
      { day: "Mon", task: "Sliding window fixed size", problems: 2 },
      { day: "Tue", task: "Sliding window variable size", problems: 3 },
      { day: "Wed", task: "Binary search classic problems", problems: 2 },
      { day: "Thu", task: "Binary search on answer space", problems: 2 },
      { day: "Fri", task: "Hard sliding/bsearch problems", problems: 2 },
      { day: "Sat", task: "Mixed from all 4 topics so far", problems: 4 },
      { day: "Sun", task: "Topic test + review", problems: 0 },
    ],
  },
  {
    week: 4, title: "Stack, Queue & Linked List", topics: ["stack", "linkedlist"],
    goals: ["Monotonic stack patterns", "Floyd's cycle detection", "Slow-fast pointer mastery"],
    dailyTasks: [
      { day: "Mon", task: "Stack theory + parentheses problems", problems: 2 },
      { day: "Tue", task: "Monotonic stack (Daily Temps, NGE)", problems: 3 },
      { day: "Wed", task: "Linked List reverse + merge", problems: 2 },
      { day: "Thu", task: "Slow-fast pointer problems", problems: 2 },
      { day: "Fri", task: "Hard stack/LL (LRU, Histogram)", problems: 2 },
      { day: "Sat", task: "Mixed revision", problems: 3 },
      { day: "Sun", task: "Weekly test + review", problems: 0 },
    ],
  },
  {
    week: 5, title: "Trees — DFS & BFS", topics: ["trees"],
    goals: ["All traversal methods", "BST operations", "LCA and path problems"],
    dailyTasks: [
      { day: "Mon", task: "Tree traversals + easy DFS", problems: 3 },
      { day: "Tue", task: "BFS / level order problems", problems: 3 },
      { day: "Wed", task: "BST problems", problems: 2 },
      { day: "Thu", task: "LCA, diameter, path sum", problems: 3 },
      { day: "Fri", task: "Hard tree problems", problems: 2 },
      { day: "Sat", task: "Full trees revision", problems: 4 },
      { day: "Sun", task: "Topic test + review", problems: 0 },
    ],
  },
  {
    week: 6, title: "Trees Advanced + Heap", topics: ["trees", "heap"],
    goals: ["Serialize/deserialize", "Top-K with heap", "Two heap median pattern"],
    dailyTasks: [
      { day: "Mon", task: "Construct trees, serialize", problems: 2 },
      { day: "Tue", task: "Heap basics + easy problems", problems: 2 },
      { day: "Wed", task: "Top-K element problems", problems: 3 },
      { day: "Thu", task: "Two heaps — median stream", problems: 2 },
      { day: "Fri", task: "Merge K sorted + Design Twitter", problems: 2 },
      { day: "Sat", task: "Mixed trees + heap", problems: 3 },
      { day: "Sun", task: "Weekly mock test", problems: 0 },
    ],
  },
  {
    week: 7, title: "Graphs — BFS/DFS", topics: ["graphs"],
    goals: ["Grid BFS/DFS", "Connected components", "Cycle detection"],
    dailyTasks: [
      { day: "Mon", task: "Graph representation + DFS basics", problems: 2 },
      { day: "Tue", task: "Number of Islands, Max Area", problems: 3 },
      { day: "Wed", task: "BFS on graphs (Rotting Oranges)", problems: 2 },
      { day: "Thu", task: "Union-Find problems", problems: 3 },
      { day: "Fri", task: "Topological sort problems", problems: 2 },
      { day: "Sat", task: "Dijkstra + shortest path", problems: 2 },
      { day: "Sun", task: "Topic test + review", problems: 0 },
    ],
  },
  {
    week: 8, title: "Backtracking + Greedy", topics: ["backtrack", "greedy"],
    goals: ["Decision tree thinking", "Pruning strategies", "Greedy vs DP distinction"],
    dailyTasks: [
      { day: "Mon", task: "Subsets + Combinations", problems: 2 },
      { day: "Tue", task: "Permutations + deduplication", problems: 2 },
      { day: "Wed", task: "Word Search + Palindrome Partition", problems: 2 },
      { day: "Thu", task: "Greedy — intervals, jumps", problems: 3 },
      { day: "Fri", task: "N-Queens + hard backtrack", problems: 2 },
      { day: "Sat", task: "Mixed revision", problems: 3 },
      { day: "Sun", task: "Weekly mock test", problems: 0 },
    ],
  },
  {
    week: 9, title: "Dynamic Programming — 1D & 2D", topics: ["dp"],
    goals: ["Memoization pattern", "1D DP (robber, stairs, decode)", "2D DP (paths, LCS)"],
    dailyTasks: [
      { day: "Mon", task: "DP theory + Fibonacci variants", problems: 2 },
      { day: "Tue", task: "House Robber series", problems: 2 },
      { day: "Wed", task: "Unique Paths, Coin Change", problems: 2 },
      { day: "Thu", task: "LCS, Edit Distance", problems: 2 },
      { day: "Fri", task: "Word Break, Decode Ways", problems: 2 },
      { day: "Sat", task: "Mixed DP problems", problems: 3 },
      { day: "Sun", task: "Topic test + review", problems: 0 },
    ],
  },
  {
    week: 10, title: "DP Advanced — Knapsack & LIS", topics: ["dp"],
    goals: ["0/1 Knapsack and variants", "LIS in O(n log n)", "Interval DP"],
    dailyTasks: [
      { day: "Mon", task: "0/1 Knapsack + Partition Sum", problems: 2 },
      { day: "Tue", task: "Unbounded Knapsack variants", problems: 2 },
      { day: "Wed", task: "LIS and variants", problems: 2 },
      { day: "Thu", task: "Palindrome DP problems", problems: 2 },
      { day: "Fri", task: "Burst Balloons, hard DP", problems: 2 },
      { day: "Sat", task: "Full DP revision", problems: 4 },
      { day: "Sun", task: "Weekly mock test", problems: 0 },
    ],
  },
  {
    week: 11, title: "Trie + Bit Manipulation", topics: ["trie", "bitwise"],
    goals: ["Implement trie from scratch", "XOR tricks", "Bitmask patterns"],
    dailyTasks: [
      { day: "Mon", task: "Trie implementation", problems: 1 },
      { day: "Tue", task: "Trie problems (search, prefix)", problems: 3 },
      { day: "Wed", task: "Bit basics + easy problems", problems: 3 },
      { day: "Thu", task: "XOR problems + missing numbers", problems: 3 },
      { day: "Fri", task: "Hard trie + bit problems", problems: 2 },
      { day: "Sat", task: "Mixed revision", problems: 3 },
      { day: "Sun", task: "Topic test", problems: 0 },
    ],
  },
  {
    week: 12, title: "Full Revision + Mock Interviews", topics: [],
    goals: ["Solve 3 problems daily mixed topics", "2 full mock contests", "Review all weak areas"],
    dailyTasks: [
      { day: "Mon", task: "Revision: Arrays + Hashing", problems: 4 },
      { day: "Tue", task: "Revision: Trees + Graphs", problems: 4 },
      { day: "Wed", task: "Revision: DP focus", problems: 4 },
      { day: "Thu", task: "Mock contest #1 (90 min)", problems: 4 },
      { day: "Fri", task: "Revision: weak topics", problems: 4 },
      { day: "Sat", task: "Mock contest #2 (120 min)", problems: 5 },
      { day: "Sun", task: "Final review + plan next phase", problems: 0 },
    ],
  },
];

